### ISSUE TITLE
Module 2 Week 2 Peer-to-peer review Sandeep Abel Ahmed Zermarden

### ISSUE THREAD

**Issue by Nedramrez** [ProgramKingAbel/Todo-List#4]
`Excellent` job so far! Just let us kindly suggest some changes:
1. Please check the Modules folder. We think that you have empty files. You can delete them if you want.
2. You can restructure your project to have more modular files. 
3. Your code can be refactored according to ES6 recommendations.

**Comment by ProgramKingAbel** [comment]
Done as recommended
